name: Run Database Deployment project
on:
  workflow_dispatch:

env:
  SWASHBUCKLE_DOTNET_CORE_VERSION: 3.1.x
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: OnlineNotebook
  AZURE_APIM_RESOURCEGROUP: OnlineNotebook20240422103748ResourceGroup
  AZURE_SQL_SERVER_NAME: onlinenotebook-database
  AZURE_SQL_DATABASE_NAME: OnlineNotebook
jobs:
  run:
    if: ${{ !github.event.act }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Setup SwashBuckle .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.SWASHBUCKLE_DOTNET_CORE_VERSION }}
      - name: Replace values in JSON file
        uses: tnikFi/json-file-transform@v1
        with:
          files: "**/appsettings.json"
          key-value-pairs: |
            ConnectionStrings.DefaultConnection=${{  secrets.DatabaseConnectionString }}
      - name: Restore
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}
      - name: Build
        run: dotnet build --configuration ${{env.CONFIGURATION}} --no-restore
        working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET }}
      - name: Whitelist GitHub Runner IP
        run: |
          $agentIP=$(curl -s https://api.ipify.org/)
          az sql server firewall-rule create --resource-group "${{env.AZURE_APIM_RESOURCEGROUP}}" --server "${{ env.AZURE_SQL_SERVER_NAME }}" --name Temp-Github-Rule --start-ip-address $agentIP --end-ip-address $agentIP
          sleep 30
      - name: Delete Azure Database
        run: az sql db delete --resource-group "${{env.AZURE_APIM_RESOURCEGROUP}}" --server "${{ env.AZURE_SQL_SERVER_NAME }}" --name onlinenotebook-database
      - name: Create Azure Database
        run: az sql db create --resource-group "${{env.AZURE_APIM_RESOURCEGROUP}}" --server "${{ env.AZURE_SQL_SERVER_NAME }}" --name onlinenotebook-database --service-objective S0
      - name: Run Database Deployment project
        run: dotnet run --project DatabaseData
      - name: Remove GitHub Runner IP from SQL Server Firewall
        run: |
          $agentIP=$(curl -s https://api.ipify.org/)
          az sql server firewall-rule delete --resource-group "${{env.AZURE_APIM_RESOURCEGROUP}}" --account-name "${{ env.AZURE_SQL_SERVER_NAME }}" --name Temp-Github-Rule
          sleep 30
      - name: Azure Logout
        run: >
          az logout
