name: Testing pipeline
on:
  push:
    branches:
      - master

env:
  SOMETHING: SOMETHING

jobs:
  first-job:
    runs-on: windows-latest
    outputs:
      test_output: ${{ steps.first-job.outputs.TEST }}
    steps:
      - name: Write to a json file
        id: first-job
        run: |
          echo "{
            \"test\": \"test\"
          }" > test.json
          echo "::set-output name=TEST::test.json"

  second-job:
    runs-on: windows-latest
    needs: first-job
    steps:
      - name: Read from a json file
        run: echo ${{ needs.first-job.outputs.test_output }} >> test.json
      - name: open the file
        run: |
         echo Get-Content test.json
